language: python

python:
  - "2.7"

jdk:
  - openjdk7

sudo: false

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.7.3-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create --yes -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip numpy scipy scikit-learn scikit-image matplotlib pytest
  - source activate test-environment
  - pip install .
  - wget http://d3kbcqa49mib13.cloudfront.net/spark-1.5.1-bin-hadoop1.tgz
  - tar -xzf spark-1.5.1-bin-hadoop1.tgz

script:
  - export SPARK_HOME=`pwd`/spark-1.5.1-bin-hadoop1
  - py.test test/ --traceconfig
